# Функции

In [ ]:
# создаем функцию
def square(number):
    result = number ** 2
    return result

print(square(10))
my_square = square(10)
print(my_square)

In [1]:
help(len)
# ?len

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
# пишем docstring к своей функции
def square(number):
    """
    this is my function

    """
    result = number ** 2
    return result

In [3]:
?square

In [ ]:
# функция без параметров
def square_2():
    user_input = int(input('Введите число'))
    result = user_input ** 2
    return result
square_2()

In [ ]:
# функция с двумя параметрамим
def power(number, number_2):
    result = number ** number_2
    return result
power(4, 2)

In [ ]:
# функция с параметром по умолчанию
def power(number, number_2=2):
    result = number ** number_2
    return result
power(4)

In [ ]:
# если не указан return, функция всегда возвращает None!
def square_3(number):
    result = number ** 2
    print(result)
#     return None
#     return
square_3(5)
# print(square_3(5))

In [ ]:
# области видимости
number = 5
power = 3

def power_2():
    number = 6
    power = 2
    return number ** power

power_2()
print(number ** power)

In [ ]:
number = 5
power = 3

def power_2():
    number = 6
    return number ** power

print(power_2())
print(number ** power)

In [ ]:
number = 5
power = 3

def power_2():
    return number ** power

power_2()

In [ ]:
def power_2():
    number = 6
    power = 2
    some_number = 1
    return number ** power
print(some_number)

In [ ]:
# global и nonlocal

name = 'James'
def say_hi():
#     global name
    name = 'Oleg'
    print('Hello', name)

say_hi()

print(name)

In [4]:
def say_hi():
    name = 'Oleg'
    def get_name():
        nonlocal name
        name = input('Введите имя')
        return name
    get_name()
    print('Hello', name)

say_hi()

Введите имяllll
Hello llll


In [5]:
# lambda-функции
func = lambda x, y: x + y
print(func(1, 2))

3


In [6]:
nums = [1, 2, 3, 4, 5]

In [7]:
even_numbers = lambda x: x % 2 == 0
odd_even_numbers = lambda x: 'even' if x % 2 == 0 else 'odd'

In [11]:
for num in nums:
    print(odd_even_numbers(num))
print(even_numbers(5))    

odd
even
odd
even
odd
False


square

In [14]:
list(filter(even_numbers, nums))

[2, 4]

In [15]:
def square(x):
    return x**2

In [16]:
for i in map(square, range(100, 105)):
    print(i)
    if i==10: break

10000
10201
10404
10609
10816


### Если аргументы функции заранее неизвестны

args kwargs

In [ ]:
def api_request(*params):
    date_start = params[0]
    date_end = params[1]
    print(params)
    print(date_start, date_end)

In [ ]:
api_request('2019-01-01', '2019-01-31')

In [17]:
def api_requets(**params):
    return params

In [18]:
api_requets(a=1, b=2, c=3)

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
def api_request(**params):
    date_start = params['date_start']
    date_end = params['date_end']
    
    print(date_start, date_end)

In [ ]:
api_request(date_end='2019-01-31', date_start='2019-01-01')

# Чтение и запись в файлы

In [ ]:
# Вариант 1

# 'r' - открыть файл для чтения
# 'w' - очистить файл и открыть для записи новых данных
# 'a' - добавить строчки к концу файла
f = open('adult.csv', 'r')
for line in f:
    print(line)
    break
    
f.close()

In [19]:
# конструкция with автоматически закрывает файл после работы с ним
# прочитать содержимое файла в список
with open('adult.csv', 'r') as f:
    content = f.readlines()

content[:5]

['age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income\n',
 '25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K\n',
 '38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K\n',
 '28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K\n',
 '44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K\n']

In [20]:
# прочитать большой файл построчно
with open('adult.csv') as f:
    for line in f:
        print(line)
        
        break

age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income



In [21]:
# подготовим файл для работы
i = 0
with open('adult.csv', 'r') as f:
    for line in f:
        print(line.strip().split(','))
        
        i = i + 1
        if i > 5:
            break

['age', 'workclass', 'fnlwgt', 'education', 'educational-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
['25', 'Private', '226802', '11th', '7', 'Never-married', 'Machine-op-inspct', 'Own-child', 'Black', 'Male', '0', '0', '40', 'United-States', '<=50K']
['38', 'Private', '89814', 'HS-grad', '9', 'Married-civ-spouse', 'Farming-fishing', 'Husband', 'White', 'Male', '0', '0', '50', 'United-States', '<=50K']
['28', 'Local-gov', '336951', 'Assoc-acdm', '12', 'Married-civ-spouse', 'Protective-serv', 'Husband', 'White', 'Male', '0', '0', '40', 'United-States', '>50K']
['44', 'Private', '160323', 'Some-college', '10', 'Married-civ-spouse', 'Machine-op-inspct', 'Husband', 'Black', 'Male', '7688', '0', '40', 'United-States', '>50K']
['18', '?', '103497', 'Some-college', '10', 'Never-married', '?', 'Own-child', 'White', 'Female', '0', '0', '30', 'United-States', '<=50K']


Хотим классифицировать жителей в файле по возрастам:
* до 18 лет - children 
* 19-65 - young
* старше 65 - retiree

In [22]:
i = 0
with open('adult.csv', 'r') as f:
    for line in f:
        age, *other_columns = line.strip().split(',')
        
        if i > 0:
            print(age)
        
        i += 1
        if i > 5:
            break

25
38
28
44
18


Добавим классификацию возрастов

In [23]:
i = 0
with open('adult.csv', 'r') as f:
    for line in f:
        age, *other_columns = line.strip().split(',')
        
        if i > 0:
            if int(age) <= 18:
                age_group = 'children'

            elif int(age) <= 60:
                age_group = 'young'

            else:
                age_group = 'retiree'
                
            print(age, age_group)
        
        i += 1
        if i > 10:
            break

25 young
38 young
28 young
44 young
18 children
34 young
29 young
63 retiree
24 young
55 young


Что тут нехорошо:
* сложно потестировать все случаи (в нашем цикле нужных случаев может и не оказаться)
* наш цикл стал довольно громоздким, а мы только начали
* эта классификация может потребоваться еще в 100500 местах кода
* данные могут быть кривыми и скрипт будет падать с ошибкой

Условия вычисления возрастной группы:
1. В строке 15 столбцов
2. Столбец с возрастом первый по счету
3. Возраст должен быть целым числом в адекватных пределах
4. Могут добавиться еще требования, о которых мы пока не знаем

In [ ]:
def age_is_correct(age, lower_age=0, upper_age=120):
    """
    Проверка корректности возраста age по следующим правилам:
    1. Целое число
    2. В адекватных пределах
    
    Возвращает True или False. Пример
    age_is_correct(15)
    True
    
    age_is_correct(121)
    False
    
    age_is_correct(-5)
    False
    """
    
    if str.isnumeric(age):
        if lower_age <= int(age) <= upper_age:
            return True
    
    return False

In [ ]:
def number_of_columns(line, separator=','):
    """Возвращает количество столбцов в строке line с разделителем separator"""
    
    return len(line.split(separator))

In [ ]:
def line_is_correct(line):
    """
    Проверка строки на корректность. Проверяются условия:
    1. В строке 15 столбцов (пригодится с упражнения)
    2. Столбец с возрастом первый по счету
    3. Возраст должен быть целым числом в адекватных пределах
    """
    age = line.strip().split(',')[0]
    
    if number_of_columns(line) == 15:
        if age_is_correct(age):
            return True
    
    return False

In [ ]:
# Добавляем функции проверки в наш цикл

In [ ]:
i = 0
with open('adult.csv', 'r') as f:
    for line in f:
        
        if line_is_correct(line):
            age, *other_columns = line.strip().split(',')
            if int(age) <= 18:
                age_group = 'children'

            elif int(age) <= 60:
                age_group = 'young'

            else:
                age_group = 'retiree'

            print(age, age_group)
        
        i += 1
        if i > 10:
            break

### Давайте вынесем классификацию возраста в отдельную функцию

In [ ]:
def age_classification(age):
    """
    Возвращает возрастную категорию для возраста age (можно передать как строку).
    Классификация категорий:
        - до 18 лет - children 
        - 19-60 - young
        - старше 65 - retiree
    
    Пример
    age_classification('18')
    'children'
    
    age_classification(65)
    'retiree'
    """
    
    if int(age) <= 18:
        return 'children'
    if int(age) <= 65:
        return 'young'
    if int(age) > 65:
        return 'retiree'
    return 'boom'

In [ ]:
age_classification(61)

In [ ]:
def main():
    with open('adult.csv', 'r') as f:
        for line in f:
            if line_is_correct(line):
                age, *_ = line.strip().split(',')
                print(age, age_classification(age))

In [ ]:
main()

### Модули

In [ ]:
import math

In [ ]:
math.factorial(5)

In [24]:
import numpy

In [25]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
from numpy import zeros
zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])